In [1]:
doc1 = "Fed is from NJ and runs hurdles"
doc2 = "Chris is from NJ and runs the 400"
doc3 = "Fed and Chris both run track in NJ"

In [2]:
docs = [doc1,doc2,doc3]
docs

['Fed is from NJ and runs hurdles',
 'Chris is from NJ and runs the 400',
 'Fed and Chris both run track in NJ']

In [3]:
uniqueTerms = { term for doc in docs for term in doc.split()}
uniqueTerms

{'400',
 'Chris',
 'Fed',
 'NJ',
 'and',
 'both',
 'from',
 'hurdles',
 'in',
 'is',
 'run',
 'runs',
 'the',
 'track'}

In [4]:
termDoc = {}

for term in uniqueTerms:
    termDoc[term] = []
    
for term in uniqueTerms:
    for doc in docs:
        if term in doc:
            termDoc[term].append(0)
        else: termDoc[term].append(1)
            
termDoc

{'runs': [0, 0, 1],
 'track': [1, 1, 0],
 'from': [0, 0, 1],
 'the': [1, 0, 1],
 'Chris': [1, 0, 0],
 '400': [1, 0, 1],
 'run': [0, 0, 0],
 'and': [0, 0, 0],
 'in': [1, 1, 0],
 'Fed': [0, 1, 0],
 'hurdles': [0, 1, 1],
 'both': [1, 1, 0],
 'is': [0, 0, 0],
 'NJ': [0, 0, 0]}

In [5]:
#Query: find all documents that contain 'chris' and 'fed;'
#just a bitwise AND

import numpy as np

#using np to wrap docs as an array 

docsArray = np.array(docs, dtype = 'object')

v1 = np.array(termDoc['Fed'])
v2 = np.array(termDoc['Chris'])

print(v1)
print(v2)
print("-------")
v3 = v1 | v2
#v3 = [1 1 1]
print(v3)




[0 1 0]
[1 0 0]
-------
[1 1 0]


In [8]:
#using list comprehension here
[doc for doc in v3*docsArray if doc]

['Fed is from NJ and runs hurdles', 'Chris is from NJ and runs the 400']